### ISSUE TITLE
Linux. Problems with launching the program.

### ISSUE THREAD

**Issue by tuchanemo** [lukasmonk/lucaschessR2#136]
Hi, I have Debian 12 installed with kernel 6.6.13.
The latest version I can install and run is LucasChessR2_10a_LINUX_WAYLAND.sh
When I want to uninstall the installed version, an error is given and
the ~/LucasChessR folder is not deleted.
![lucaschessR2 10a_wayland_uninstall](https://github.com/lukasmonk/lucaschessR2/assets/20821814/c6f92f35-82f0-46d6-9ee8-1563a1bc6090)

I don't have the program versions working:
LucasChessR2_11b_LINUX.sh
LucasChessR2_12c_LINUX.sh
When trying to play without installation gives an error.
![lucaschessR2 12c_play](https://github.com/lukasmonk/lucaschessR2/assets/20821814/213c9b67-7663-4f9a-bbdf-13adc0c1ea18)

**Comment by tuchanemo** [comment]
I renamed the old folder and ran the install. The installation went through, I pressed the "Close" key. On the console I see the following message and nothing else happens, the program window does not open.
![lucaschessК2 12c console](https://github.com/lukasmonk/lucaschessR2/assets/20821814/3d757c9d-8f34-4e7e-910f-b95e858a774b)

**Comment by lukasmonk** [comment]
I have no idea.
There is an alternative: https://lucaschess.blogspot.com/2024/03/installing-lucas-chess-on-linux-from.html

**Comment by tuchanemo** [comment]
I did everything according to the link provided. The installer also installed miniconda3. I go to the ~/lucaschess folder and run the script LucasR.sh. Something happens for a while, then the command line prompt appears and that's it. The program window does not open.

**Comment by lukasmonk** [comment]
There is a file = bug.log, maybe it will show what's going on, if it contains more than one line, please write a message showing it.
If it only has one line, you can edit Lucas.sh and delete the line:
export XDG_SESSION_TYPE=xcb

**Comment by tuchanemo** [comment]
Here's the file bug.log
[bug.log](https://github.com/lukasmonk/lucaschessR2/files/14655721/bug.log)

**Comment by lukasmonk** [comment]
The problem seems to be in the ct800 engine version.
Copy the attached file unzipped in the programme folder. /bin/OS/linux/Engines/ct800/
[CT800-1.45.uci_options.zip](https://github.com/lukasmonk/lucaschessR2/files/14656397/CT800-1.45.uci_options.zip)

**Comment by tuchanemo** [comment]
Traceback (most recent call last):
  File "LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 90, in run_gui
    procesador.start_with_user(user)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Procesador.py", line 124, in start_with_user
    self.configuration.start()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Config/Configuration.py", line 400, in start
    self.relee_engines()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Config/Configuration.py", line 343, in relee_engines
    self.dic_engines = OSEngines.read_engines(Code.folder_engines)
  File "/home/xxx/lucaschess/lucaschessR2/bin/OS/linux/OSEngines.py", line 143, in read_engines
    mas("igel", "Volodymyr Shcherbyna", "3.0.0", "https://github.com/vshcherbyna/igel/", "Igel-3.0.10", 3402,
  File "/home/xxx/lucaschess/lucaschessR2/bin/OS/linux/OSEngines.py", line 16, in mas
    engine.set_uci_option("Log", "false")
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/Engines.py", line 109, in set_uci_option
    li_uci_options = self.li_uci_options()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/Engines.py", line 235, in li_uci_options
    self.read_uci_options()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/Engines.py", line 191, in read_uci_options
    engine = EngineRunDirect.DirectEngine("-", self.path_exe, args=self.args)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/EngineRunDirect.py", line 75, in __init__
    self.ucinewgame()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/EngineRunDirect.py", line 146, in ucinewgame
    self.put_line("ucinewgame")
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Engines/EngineRunDirect.py", line 82, in put_line
    self.stdin.flush()
BrokenPipeError: [Errno 32] Channel break

**Comment by lukasmonk** [comment]
Now is Igel.
In attach a zip file to unzip in . /bin/OS/linux: 
[Engines.zip](https://github.com/lukasmonk/lucaschessR2/files/14656656/Engines.zip)

**Comment by tuchanemo** [comment]
Traceback (most recent call last):
  File "LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 90, in run_gui
    procesador.start_with_user(user)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Procesador.py", line 126, in start_with_user
    Code.runSound.read_sounds()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Sound/Sound.py", line 104, in read_sounds
    self.write_sounds()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Sound/Sound.py", line 82, in write_sounds
    wav = self.relations[key]["WAV_KEY"] + ".wav"
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Sound/Sound.py", line 139, in relations
    add("MC", _("Beep after move"), "BEEP")
TypeError: 'NoneType' object is not callable

**Comment by lukasmonk** [comment]
My hypothesis, it is possible that the problem is that the user folder has characters that make some files unreachable.
To check this, one possibility would be to create a folder in Home, with a name with ascci characters, for example alex, and with full permissions for your user, and copy/ the lucaschess folder into that folder.

**Comment by tuchanemo** [comment]
my home folder name is made entirely of ascii characters

**Comment by lukasmonk** [comment]
Sorry, I had seen some messages with non-ascii characters, and I have not checked.

**Comment by lukasmonk** [comment]
Where did you make the last attempt, in the version that installs miniconda?

**Comment by tuchanemo** [comment]
I downloaded the installation file from the link https://github.com/lukasmonk/lucaschessR2/releases/download/R2.12c/LinuxInstaller.sh

**Comment by lukasmonk** [comment]
That is correct, and should work.
I attach a new file to unzip in UserData folder (it creates the Sounds folder).
[Sounds.zip](https://github.com/lukasmonk/lucaschessR2/files/14657349/Sounds.zip)

The problem is that I don't know why it doesn't work. Maybe there is some incompatibility with some engines, like ct800 and igel, which I would fix by recompiling them. Now it doesn't read the resources. This file pops the last error, to see if the next error gives me some clue to understand the problem. Tomorrow I'll make a comparison between the wayland versions and this one, maybe I'll find something.

**Comment by tuchanemo** [comment]
Traceback (most recent call last):
  File "LucasR.py", line 18, in <module>
    Code.Base.Init.init()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 123, in run_gui
    procesador.iniciar_gui()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/Procesador.py", line 180, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 28, in __init__
    self.base = WBase.WBase(self, manager)
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 84, in __init__
    self.create_toolbar()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 124, in create_toolbar
    dic_opciones = self.dic_opciones_tb()
  File "/home/xxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 153, in dic_opciones_tb
    TB_PLAY: (_("Play"), Iconos.Libre()),
TypeError: 'NoneType' object is not callable

**Comment by lukasmonk** [comment]
Attached is LucasR.py changed to try to fix this latest bug.
[LucasR.zip](https://github.com/lukasmonk/lucaschessR2/files/14662339/LucasR.zip)
You have to unzip it in the bin folder replacing LucasR.py
Then remove bug.log and launch again LucasR.sh.

**Comment by lukasmonk** [comment]
I have dusted off the virtual machine where I generated the WAYLAND version, and I have prepared a compilation:
https://drive.google.com/file/d/1ztydF_iN5f8SSutHtefnxZk1k2v5L__3/view?usp=drive_link

**Comment by lukasmonk** [comment]
Please download the 12c installer again and try to install with it.
https://github.com/lukasmonk/lucaschessR2/releases/download/R2.12c/LucasChessR2_12c_LINUX.sh

I finally managed to replicate the problem in a virtual machine. I had to downgrade to a library (psutil), and after recompiling everything again it worked in that virtual machine.

**Comment by tuchanemo** [comment]
I replaced the file LucasR.py and ran the script LucasR.sh The program window did not open.
Here is the log
Traceback (most recent call last):
  File "LucasR.py", line 24, in <module>
    Code.Base.Init.init()
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/Base/Init.py", line 18, in init
    resp = LucasChessGui.run_gui(main_procesador)
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/MainWindow/LucasChessGui.py", line 123, in run_gui
    procesador.iniciar_gui()
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/Procesador.py", line 180, in iniciar_gui
    self.main_window = MainWindow.MainWindow(self)
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/MainWindow/MainWindow.py", line 28, in __init__
    self.base = WBase.WBase(self, manager)
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 84, in __init__
    self.create_toolbar()
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 124, in create_toolbar
    dic_opciones = self.dic_opciones_tb()
  File "/home/xxxx/lucaschess/lucaschessR2/bin/Code/MainWindow/WBase.py", line 153, in dic_opciones_tb
    TB_PLAY: (_("Play"), Iconos.Libre()),
TypeError: 'NoneType' object is not callable

Версия LucasChessR2_12c_LINUX.sh
Все работает.
![lucaschessК2 12c1 console](https://github.com/lukasmonk/lucaschessR2/assets/20821814/bddae2ff-2b4f-4e96-9fc9-76e904ab6cff)
![lucaschessК2 12c1 console_1](https://github.com/lukasmonk/lucaschessR2/assets/20821814/b5909abd-cbbd-426b-94a5-83f703cc7e4f)

Play without installation works. Installing the program works. Uninstalling the program works. Thank you.

**Comment by tuchanemo** [comment]
New version of LucasChessR2_12c_LINUX.sh.
does not work. Here is the log.
Version R 2.12c
Traceback (most recent call last):
  File "Launcher.py", line 53, in <module>
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/LucasR.py", line 18, in <module>
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Base/Init.py", line 18, in init
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/MainWindow/LucasChessGui.py", line 90, in run_gui
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Procesador.py", line 124, in start_with_user
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Config/Configuration.py", line 400, in start
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Config/Configuration.py", line 343, in relee_engines
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/OS/linux/OSEngines.py", line 92, in read_engines
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/OS/linux/OSEngines.py", line 16, in mas
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/Engines.py", line 109, in set_uci_option
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/Engines.py", line 235, in li_uci_options
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/Engines.py", line 191, in read_uci_options
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/EngineRunDirect.py", line 75, in __init__
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/EngineRunDirect.py", line 146, in ucinewgame
  File "/home/lucas/pyLCR2/genlinux/LucasChessR/bin/Code/Engines/EngineRunDirect.py", line 82, in put_line
BrokenPipeError: [Errno 32] Обрыв канала

**Comment by lukasmonk** [comment]
I forgot that there are some engines that do not work on all pcs.
I've redone the installer to take this into account.

**Comment by lukasmonk** [comment]
Great!
I will try to find out what is going on with ct800 and igel.
Thank you very much for your help and patience.

**Comment by tuchanemo** [comment]
Thank you for the program.
