### ISSUE TITLE
a specific error

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR2#21]
Hi Lucas,
I am facing a very specific error which occurs only at one position in "Moves tree". Look at the position below.
![image](https://user-images.githubusercontent.com/60097814/179547676-7bf4c0ca-ef68-4603-8afc-2cecb704bd6b.png)
Moves tree doesn't open at Black's 7th move here. This is only happening here, NOT anywhere else. At present, this is a very small problem but if this starts to happen with some other moves/positions then it would be troublesome. Any clue what is happening?

**Comment by lukasmonk** [comment]
I have no idea, I can´t replicate it:
![image](https://user-images.githubusercontent.com/6254278/179555286-d093bf61-3bd1-4618-bb6c-e17eb88e260f.png)

The file bug.log in the bin folder, perhaps has the information.

**Comment by futurelauncher** [comment]
Hi,
The file has following content. I couldn't make out what is causing the error.

Version R 2.01c2
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\Procesador.py", line 548, in run_action
  File "LucasChessR\bin\Code\Procesador.py", line 743, in menu_tools
  File "LucasChessR\bin\Code\Procesador.py", line 777, in menuTools_run
  File "LucasChessR\bin\Code\Procesador.py", line 868, in database
  File "LucasChessR\bin\Code\Databases\WindowDatabase.py", line 25, in __init__
  File "LucasChessR\bin\Code\Databases\DBgames.py", line 46, in __init__
sqlite3.OperationalError: unable to open database file
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 634, in analizar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 852, in analizar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 902, in quitaAnalisis
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 541, in goto
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 634, in analizar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 852, in analizar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 902, in quitaAnalisis
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 541, in goto
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 652, in mostrar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 510, in mostrarOcultar
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 541, in goto
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 546, in seleccionado
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 784, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 717, in muestra
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 697, in ponValores
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 389, in edited
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 449, in editAnalisis
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 389, in edited
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 449, in editAnalisis
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 389, in edited
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 449, in editAnalisis
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 74, in etiPuntos
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 204, in nomAnalisis
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range
Traceback (most recent call last):
  File "LucasChessR\bin\Code\MainWindow\WBase.py", line 354, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 140, in run_action
  File "LucasChessR\bin\Code\ManagerGame.py", line 316, in utilities_gs
  File "LucasChessR\bin\Code\Manager.py", line 1512, in utilidades
  File "LucasChessR\bin\Code\Manager.py", line 1675, in arbol
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 740, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 167, in __init__
  File "LucasChessR\bin\Code\QT\WindowArbol.py", line 249, in ponAnalisisActivo
IndexError: list index out of range

**Comment by futurelauncher** [comment]
I figured out the following error finally.
IndexError: list index out of range
Why is it happening? How to resolve it?

**Comment by lukasmonk** [comment]
Fixed in next version.
