### ISSUE TITLE
[feature] add uci engine as bat file

### ISSUE THREAD

**Issue by Xyrio** [lukasmonk/lucaschessR2#56]
when i try to ad a bat file that calls the engine, after a few seconds it freezes and crashes when i click on "One moment please..." ui.

### not working:

i use the command option:
c:\windows\system32\cmd.exe
/C
c:\stockfish.bat

content of stockfish.bat:
<absolute path to stockfish 15.1 exe>

running bat from console works fine
all paths are absolute

running lucasR2 as admin didnt help.

i also tried making an exe file from a py file then using that exe directly and also as command.
the exe calls a bat file
but same freeze and crash

i tried the Engine.py from #45 but no difference

### working:
adding stockfish directly as exe works.

command using python.exe with a py script as parameter works
<path_to_python.exe>
<python_file.py>

### spec:

using windows 7 64bit

**Comment by lukasmonk** [comment]
This is not supported and will not be supported in the future.

**Comment by Xyrio** [comment]
is it a technical limitation?
i might try to program it myself.

**Comment by Xyrio** [comment]
```
  File "...\bin\Code\Engines\EngineRunDirect.py", line 55, in __init__
    self.process = subprocess.Popen(xargs, stdout=subprocess.PIPE, stdin=subprocess.PIPE, startupinfo=startupinfo)
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\subprocess.py", line 753, in __init__
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1107, in _get_handles
  File "D:\obj\windows-release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1119, in _make_inheritable
OSError: [WinError 6] The handle is invalid
```
no clue why it does not want to work with either cmd.exe
(64bit) C:\Windows\System32\cmd.exe
(32bit) C:\Windows\SysWOW64\cmd.exe
(yea the folder with 32 in its name has 64bit programs and the one with 64 has 32bit programs. windows logic)

trying to use the non exe source but have not figured out how to get this FasterCode working:
```
Traceback (most recent call last):
  File "LucasR.py", line 17, in <module>
    import Code.Base.Init
  File "...\bin\Code\Base\Init.py", line 5, in <module>
    from Code import Procesador
  File "...\bin\Code\Procesador.py", line 10, in <module>
    from Code import ManagerEntPos
  File "...\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "...\bin\Code\ManagerEntPos.py", line 5, in <module>
    from Code import FNSLine
  File "...\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "...\bin\Code\FNSLine.py", line 1, in <module>
    from Code.Base import Game, Position
  File "...\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "...\bin\Code\Base\Game.py", line 1, in <module>
    import FasterCode
  File "...\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'FasterCode'
```

**Comment by Xyrio** [comment]
in 2.05 same freeze happens because the exception is not caught. so the message box with `The file %1 does not correspond to a UCI engine type.` from `...\bin\Code\Engines\WConfEngines.py` does not appear

**Comment by lukasmonk** [comment]
FasterCode: .\bin\_fastercode\ in source code.

**Comment by Xyrio** [comment]
i am not too familiar with python. read a bit about pyd stuff. as far as i read it is supposed to be like a DLL for python.

the FasterCode.cp37-win32.pyd already exists 

i set the PYTHONPATH env var to the folder with FasterCode.cp37-win32.pyd but didnt do anything.
still same error as above:
ModuleNotFoundError: No module named 'FasterCode'

compiling c code myself is too much of a hassle.

used a copy renamed to FasterCode.pyd and the dlls from bin\OS\win32\DigitalBoards\ copied all to bin.
but then it gives me this error:
```
(.ve_3_7) S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin>python LucasR.py
Traceback (most recent call last):
  File "LucasR.py", line 17, in <module>
    import Code.Base.Init
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\Base\Init.py", line 5, in <module>
    from Code import Procesador
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\Procesador.py", line 10, in <module>
    from Code import ManagerEntPos
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\ManagerEntPos.py", line 5, in <module>
    from Code import FNSLine
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\FNSLine.py", line 1, in <module>
    from Code.Base import Game, Position
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\Base\Game.py", line 1, in <module>
    import FasterCode
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\.ve_3_7\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung.
```

also added all the dll/pyd stuff from 2.05 release to my source bin.
but then it is this error.
```
(.ve_3_7) S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin>python LucasR.py
Traceback (most recent call last):
  File "LucasR.py", line 17, in <module>
    import Code.Base.Init
  File "S:\CODE\Projects\_game\_chess\lucaschessR2_py\bin\Code\__init__.py", line 2, in <module>
    import ssl
  File "C:\Progz\_programming\python\WPy64-3760\python-3.7.6.amd64\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: %1 ist keine zulässige Win32-Anwendung.
```

if there no way to run in more pure python mode that doesnt require all the extras then i guess it is not ment to be run by me :)

ideally one has a script to setup stuff and then it should run.
like pip install -r requirements.txt
or some other script.

anyway i tested with 2.04 and replacing pyc files with the py equivalent. but running bat, cmd.exe or exe converted from py files always gives exception above:
OSError: [WinError 6] The handle is invalid

might be a python thing i dont know.

so for now i give up.

using command with python.exe and a custom python script is close enough to what i need. (for running toy python chess engine)

since you dont intend to add this feature i close the issue.

**Comment by Xyrio** [comment]
you could fix the freezing of the gui, if you catch the OSError exception (see trace above)

then instead the message popups is shown from WConfEngines.py > WConfExternals ...
QTUtil2.message_bold(self, _X(_("The file %1 does not correspond to a UCI engine type."), command))

**Comment by Xyrio** [comment]
[ImportError: DLL load failed: %1 is not a valid Win32 application](https://forums.couchbase.com/t/importerror-dll-load-failed-1-is-not-a-valid-win32-application/32675)

so it seems to be because of a mismatch of python 64bit with 32bit dlls i copied over.

**Comment by lukasmonk** [comment]
c:\Program Files (x86)\Python37-32\

**Comment by Xyrio** [comment]
ok confirmed 32bit necessary
(setup because needs pip) https://www.python.org/downloads/release/python-379/
(just exe extracting) https://sourceforge.net/projects/winpython/files/WinPython_3.7/3.7.7.1/
