### ISSUE TITLE
Problems to run LucasR.py

### ISSUE THREAD

**Issue by ghost** [lukasmonk/lucaschessR2#63]
I have been following the [installation](https://lucaschess.blogspot.com/2021/07/linux-tutorial-for-creating-installer.html) steps, and everything was going well until the moment of executing `lucasR.py`.

Here is the problem...
```
> python LucasR.py
Traceback (most recent call last):
  File "/home/cristian/lucaschessR2-main/bin/LucasR.py", line 17, in <module>
    import Code.Base.Init
  File "/home/cristian/lucaschessR2-main/bin/Code/Base/Init.py", line 5, in <module>
    from Code import Procesador
  File "/home/cristian/lucaschessR2-main/bin/Code/Procesador.py", line 10, in <module>
    from Code import ManagerEntPos
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/cristian/lucaschessR2-main/bin/Code/ManagerEntPos.py", line 5, in <module>
    from Code import FNSLine
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/cristian/lucaschessR2-main/bin/Code/FNSLine.py", line 1, in <module>
    from Code.Base import Game, Position
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/cristian/lucaschessR2-main/bin/Code/Base/Game.py", line 1, in <module>
    import FasterCode
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'FasterCode'
>
```
I already tried to install the `FasterCode` module and this is the result...
```
❯ pip install FasterCode
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement FasterCode (from versions: none)
ERROR: No matching distribution found for FasterCode
>
```
I also repeated these steps using `sudo` but it didn't work either.

I checked [this](https://github.com/lukasmonk/lucaschessR2/issues/29) but it wasn't much help

P.S.
I am using:
- python 3.10.8
- pip 22.3.1
- Manjaro with kernel 5.15.85-1

**Comment by lukasmonk** [comment]
It is tested only with python 3.8. FasterCode is already created to this version.
FasterCode, can be generated to python 3.10:
```
cd bin/_fastercode
sh ./linux64.sh
```
