### ISSUE TITLE
Wayland edition cannot be installed on Debian 11 (bullseye)

### ISSUE THREAD

**Issue by keikiki** [lukasmonk/lucaschessR2#86]
I cannot install the Wayland edition of _Lucas Chess R 2.06b_ on Debian 11 (bullseye).

When I execute `./LucasChessR2_06b_LINUX_WAYLAND.sh` I get the following output:
```
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Lucas Chess R 2.06b  100%  
PySide2/__init__.py: Unable to import shiboken2 from /tmp/selfgz605140/bin/base_library.zip, /tmp/selfgz605140/bin/lib-dynload, /tmp/selfgz605140/bin
Traceback (most recent call last):
File "setup_linux.py", line 8, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
File "PySide2/__init__.py", line 107, in <module>
File "PySide2/__init__.py", line 58, in _setupQtDirectories
File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
File "shiboken2/__init__.py", line 27, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/selfgz605140/bin/libstdc++.so.6)
[605817] Failed to execute script 'setup_linux' due to unhandled exception!
```

A short check with `ldd --version | grep GLIBC` shows the issue:
```
ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
```

Does anyone have an idea how I can install the Wayland edition on my system?

**Comment by lukasmonk** [comment]
The only way would be to create the executable on the computer itself . [doc](http://lucaschess.blogspot.com/2021/07/linux-tutorial-for-creating-installer.html)
Or if you have python 3.7+ installed in your pc, downloading the sources, and the requeriments.
