### ISSUE TITLE
Opening Move tree at the end of an opening training raises an error if on a move of the non-trained color.

### ISSUE THREAD

**Issue by chemtov** [lukasmonk/lucaschessR2#87]
Hi,

context: finish a static training with black (for instance) -> select a white move -> Utilities -> Moves tree: nothing happen and in "bug.log" we have:

```
Traceback (most recent call last):
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/MainWindow/WBase.py", line 360, in run_action
  File "/home/lk/Público/PyLCR/genlinux/LucasChessR/bin/Code/Openings/ManagerOPLStatic.py", line 197, in run_action
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Manager.py", line 1588, in utilities
  File "/home/lucas/Público/PyLCR/genlinux/LucasChessR/bin/Code/Manager.py", line 1773, in arbol
  File "/home/lk/Público/PyLCR/genlinux/LucasChessR/bin/Code/QT/WindowArbol.py", line 731, in __init__
  File "/home/lk/Público/PyLCR/genlinux/LucasChessR/bin/Code/QT/WindowArbol.py", line 589, in __init__
  File "/home/lk/Público/PyLCR/genlinux/LucasChessR/bin/Code/QT/WindowArbol.py", line 319, in __init__
  File "/home/lk/Público/PyLCR/genlinux/LucasChessR/bin/Code/QT/WindowArbol.py", line 369, in ponMoves
AttributeError: 'WindowArbol' object has no attribute 'splitter'

```

It's R 2.06b/linux/wayland on Fedora 37.

Regards,

**Comment by lukasmonk** [comment]
Fixed, to the next update. Thanks.
